scenefun3d_dir: /home/kumaraditya/datasets/scenefun3d_v2/val
scenefun3d_gt_dir: /home/kumaraditya/datasets/scenefun3d_v2/val_gt
scenefun3d_pred_dir: /home/kumaraditya/datasets/scenefun3d_v2/val_pred
scenefun3d_pseudo_pred_dir: /home/kumaraditya/datasets/scenefun3d_v2/val_pseudo_pred

map_dir: /home/kumaraditya/datasets/scenefun3d_v2/task_eval/scenefun3d_420693_cg-detector_2025-09-02-15-48-43.851663

results_dir: /home/kumaraditya/scenefun3d/concept_nodes/output/recall_results
stat_plots_dir: /home/kumaraditya/scenefun3d/concept_nodes/output/stats_plots
